import type { Domain, KpiSummary, Persona, RootCase } from "./types";

export const personas: Persona[] = [
  { id: "retail-ops", name: "Regional Ops Manager", kind: "operational", scope: "South Region · real-time" },
  { id: "retail-vp", name: "VP Merchandising", kind: "strategic", scope: "Network-wide · weekly trend" },
  { id: "sc-ops", name: "DC Ops Manager", kind: "operational", scope: "DC-North · real-time" },
  { id: "sc-vp", name: "VP Supply Chain", kind: "strategic", scope: "Network-wide · weekly trend" },
];

export const kpis: KpiSummary[] = [
  {
    id: "retail-revenue",
    name: "Revenue",
    domain: "retail",
    value: "₹74.2L",
    unit: "/ week",
    delta: -8,
    deltaLabel: "-8% WoW",
    trend: [82, 84, 83, 85, 81, 79, 74],
    tier: "EXPLAINED",
    segment: "South Region · Mobile",
    updatedAt: "2 min ago",
  },
  {
    id: "retail-conversion",
    name: "Conversion Rate",
    domain: "retail",
    value: "2.31%",
    unit: "",
    delta: -1.4,
    deltaLabel: "-1.4pp WoW",
    trend: [2.6, 2.6, 2.5, 2.6, 2.5, 2.4, 2.3],
    tier: "EXPLAINED",
    segment: "South Region · Mobile",
    updatedAt: "2 min ago",
  },
  {
    id: "retail-aov",
    name: "Average Order Value",
    domain: "retail",
    value: "₹1,842",
    unit: "",
    delta: 0.6,
    deltaLabel: "+0.6% WoW",
    trend: [1810, 1820, 1815, 1830, 1825, 1838, 1842],
    tier: "UNEXPLAINED",
    segment: "Network-wide",
    updatedAt: "6 min ago",
  },
  {
    id: "retail-returns",
    name: "Return Rate",
    domain: "retail",
    value: "4.9%",
    unit: "",
    delta: 0.3,
    deltaLabel: "+0.3pp WoW",
    trend: [4.5, 4.6, 4.5, 4.7, 4.6, 4.8, 4.9],
    tier: "SUSPECTED",
    segment: "West Region · Apparel",
    updatedAt: "12 min ago",
  },
  {
    id: "sc-otif",
    name: "OTIF",
    domain: "supply-chain",
    value: "87.1%",
    unit: "",
    delta: -9,
    deltaLabel: "-9pp WoW",
    trend: [96, 95, 96, 95, 93, 89, 87],
    tier: "EXPLAINED",
    segment: "Northeast · DC-North",
    updatedAt: "4 min ago",
  },
  {
    id: "sc-stockout",
    name: "Stockout Rate",
    domain: "supply-chain",
    value: "3.2%",
    unit: "",
    delta: 0.4,
    deltaLabel: "+0.4pp WoW",
    trend: [2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2],
    tier: "SUSPECTED",
    segment: "West · DC-West",
    updatedAt: "9 min ago",
  },
  {
    id: "sc-leadtime",
    name: "Supplier Lead-Time Variance",
    domain: "supply-chain",
    value: "±1.8 days",
    unit: "",
    delta: 0.2,
    deltaLabel: "+0.2d WoW",
    trend: [1.4, 1.5, 1.5, 1.6, 1.6, 1.7, 1.8],
    tier: "UNEXPLAINED",
    segment: "Network-wide",
    updatedAt: "18 min ago",
  },
  {
    id: "sc-cost",
    name: "Cost-per-Order",
    domain: "supply-chain",
    value: "₹142",
    unit: "",
    delta: -1.1,
    deltaLabel: "-1.1% WoW",
    trend: [148, 147, 146, 145, 144, 143, 142],
    tier: "EXPLAINED",
    segment: "Network-wide",
    updatedAt: "20 min ago",
  },
];

export const cases: Record<string, RootCase> = {
  "retail-revenue": {
    id: "case-retail-revenue-01",
    kpiId: "retail-revenue",
    domain: "retail",
    title: "Revenue falls 8% in South region this week",
    detect: {
      headline: "Revenue is 8% below its STL-expected baseline for South Region",
      statSignificance: "Residual exceeds 2.3σ control limit (bar: 2.0σ)",
      businessImpact: "~₹6L at-risk weekly revenue (bar: ₹2L)",
    },
    decompose: [
      { dimension: "Region", narrowedTo: "South", note: "Other regions flat WoW" },
      { dimension: "Product category", narrowedTo: "Footwear", note: "78% of the drop isolates here" },
      { dimension: "Traffic source", narrowedTo: "Mobile", note: "Desktop conversion unaffected" },
    ],
    evidence: [
      {
        kind: "structured",
        label: "Price & promo ledger",
        detail: "No price or promo changes in South Footwear this week",
        contribution: 0,
        citation: "marketing_spend_ledger · wk 2026-08-17",
        aligned: false,
      },
      {
        kind: "unstructured",
        label: "Support tickets",
        detail: "4.2x spike in \"site slow on checkout\" complaints, mobile only, South region",
        contribution: 78,
        citation: "support_tickets #8841, #8852, #8879 (3 cited)",
        aligned: true,
      },
      {
        kind: "exogenous",
        label: "Local events / weather",
        detail: "No coinciding event or weather anomaly in the window",
        contribution: 0,
        citation: "exogenous_calendar · South, wk 2026-08-17",
        aligned: false,
      },
    ],
    tier: "EXPLAINED",
    contributionTotal: 78,
    narratives: {
      "retail-ops":
        "Mobile checkout is broken for South region shoppers right now — this is a P1 engineering bug, not a demand or pricing problem. Support tickets confirm it started Tuesday. Escalate today; every day this sits open costs roughly ₹85K in the region.",
      "retail-vp":
        "This week's South region dip is a single, fixable technical regression (mobile checkout latency), not a demand or competitive signal — no action needed on pricing or assortment. Network-wide revenue trend outside this segment remains on-plan. Recommend confirming resolution before next week's review.",
    },
    action: {
      driver: "Mobile checkout regression (South, Footwear) — 78% contribution",
      lever: "Checkout performance / release rollback",
      action: "Escalate to engineering as a P1 checkout bug; check latest mobile release for regressions",
      impact: "~₹6L at-risk weekly revenue recovered once resolved",
      owner: "Head of Mobile Engineering",
      confidence: "EXPLAINED · 78%",
      monitor: "Mobile checkout completion rate, South region — check back in 48 hours",
    },
    checkBackDate: "2026-08-24",
  },
  "sc-otif": {
    id: "case-sc-otif-01",
    kpiId: "sc-otif",
    domain: "supply-chain",
    title: "OTIF falls 9pp in Northeast region this week",
    detect: {
      headline: "OTIF is 9pp below its STL-expected baseline for Northeast",
      statSignificance: "Residual exceeds 2.6σ control limit (bar: 2.0σ)",
      businessImpact: "~₹3.2L at-risk SLA credits (bar: ₹1L)",
    },
    decompose: [
      { dimension: "Region", narrowedTo: "Northeast", note: "Other regions within normal band" },
      { dimension: "DC", narrowedTo: "DC-North", note: "Other DCs in region unaffected" },
      { dimension: "Lane", narrowedTo: "2 of 14 lanes", note: "Concentrated, not network-wide" },
    ],
    evidence: [
      {
        kind: "structured",
        label: "Supplier PO / lead-time data",
        detail: "No lead-time change recorded for affected lanes",
        contribution: 0,
        citation: "erp_po_ledger · wk 2026-08-17",
        aligned: false,
      },
      {
        kind: "unstructured",
        label: "Carrier / DC incident tickets",
        detail: "2-day depot closure logged on exactly the 2 affected lanes",
        contribution: 46,
        citation: "carrier_incident #NE-2291",
        aligned: true,
      },
      {
        kind: "exogenous",
        label: "Festival / road-closure calendar",
        detail: "Festival-driven highway closure on the same dates, same lanes",
        contribution: 38,
        citation: "regional_calendar · Northeast, 2026-08-18 to 2026-08-20",
        aligned: true,
      },
    ],
    tier: "EXPLAINED",
    contributionTotal: 84,
    narratives: {
      "sc-ops":
        "Two lanes out of DC-North are down because of a depot closure that overlapped with a festival road closure — not a carrier SLA failure. Reroute through DC-Central for the next 5 days rather than escalating to the carrier. This is temporary and location-specific.",
      "sc-vp":
        "The Northeast OTIF dip is fully explained by a short, localized disruption (2 of 14 lanes, DC-North) coinciding with a known festival closure — not a systemic carrier or supplier issue. No network-wide lever needed; DC-North ops is already rerouting. Expect recovery within the week.",
    },
    action: {
      driver: "Depot closure + festival road closure, DC-North lanes 6 & 9 — 84% combined contribution",
      lever: "Lane rerouting",
      action: "Reroute affected lanes through DC-Central for 5 days rather than escalate to the carrier as an SLA breach",
      impact: "~₹3.2L at-risk SLA credits avoided",
      owner: "DC-North Ops Manager",
      confidence: "EXPLAINED · 84%",
      monitor: "OTIF on lanes 6 & 9 — check back next Monday",
    },
    checkBackDate: "2026-08-25",
  },
  "retail-returns": {
    id: "case-retail-returns-01",
    kpiId: "retail-returns",
    domain: "retail",
    title: "Return rate up 0.3pp in West region, Apparel",
    detect: {
      headline: "Return rate is 0.3pp above baseline for West Region · Apparel",
      statSignificance: "Residual exceeds 2.1σ control limit (bar: 2.0σ)",
      businessImpact: "~₹1.4L in incremental return processing cost (bar: ₹1L)",
    },
    decompose: [
      { dimension: "Region", narrowedTo: "West", note: "Other regions flat" },
      { dimension: "Product category", narrowedTo: "Apparel", note: "Isolated to one category" },
    ],
    evidence: [
      {
        kind: "structured",
        label: "Sizing / SKU catalog",
        detail: "One new supplier SKU batch introduced two weeks ago, no confirmed sizing defect yet",
        contribution: 35,
        citation: "pos_sku_catalog · West, batch WB-2245",
        aligned: true,
      },
      {
        kind: "unstructured",
        label: "Product reviews",
        detail: "Handful of reviews mention \"runs small\" but below the volume needed for high confidence",
        contribution: 22,
        citation: "product_reviews (6 mentions, single SKU family)",
        aligned: true,
      },
      {
        kind: "exogenous",
        label: "Local events / weather",
        detail: "No coinciding signal",
        contribution: 0,
        citation: "exogenous_calendar · West, wk 2026-08-17",
        aligned: false,
      },
    ],
    tier: "SUSPECTED",
    contributionTotal: 57,
    narratives: {
      "retail-ops":
        "A plausible cause — a new supplier batch that may run small — but evidence is still thin (single SKU family, only 6 review mentions). Don't relabel sizing yet; pull 20 more days of returns data on that batch before acting.",
      "retail-vp":
        "This looks like an isolated supplier-batch sizing issue in West Apparel, not a broader quality trend — but we don't have enough evidence to confirm yet. Recommend holding off on supplier action pending more data.",
    },
    action: {
      driver: "Candidate: supplier batch WB-2245 sizing — 57% combined contribution (below EXPLAINED bar)",
      lever: "Supplier quality / sizing chart",
      action: "Do not act yet — pull 20 more days of return-reason data tagged to batch WB-2245",
      impact: "Avoids a premature supplier escalation if the signal doesn't hold",
      owner: "Category Manager, Apparel",
      confidence: "SUSPECTED · 57%",
      monitor: "Return rate + review volume, batch WB-2245 — check back in 10 days",
    },
    checkBackDate: "2026-09-01",
  },
  "retail-aov": {
    id: "case-retail-aov-01",
    kpiId: "retail-aov",
    domain: "retail",
    title: "AOV drift, network-wide — no clear driver",
    detect: {
      headline: "AOV is trending up slightly but stays within normal seasonal variance envelope",
      statSignificance: "Residual at 1.1σ — below the 2.0σ materiality bar",
      businessImpact: "Below the ₹2L business-impact floor",
    },
    decompose: [
      { dimension: "Region", narrowedTo: "No single region isolates the movement", note: "Distributed evenly" },
      { dimension: "Product category", narrowedTo: "No single category isolates the movement", note: "Distributed evenly" },
    ],
    evidence: [
      {
        kind: "structured",
        label: "Marketing spend ledger",
        detail: "No bundle or upsell campaign change",
        contribution: 12,
        citation: "marketing_spend_ledger · wk 2026-08-17",
        aligned: false,
      },
      {
        kind: "unstructured",
        label: "Support tickets / reviews",
        detail: "No thematic signal above noise floor",
        contribution: 8,
        citation: "support_tickets, product_reviews · low relevance",
        aligned: false,
      },
      {
        kind: "exogenous",
        label: "Local events / weather",
        detail: "No coinciding signal",
        contribution: 0,
        citation: "exogenous_calendar · network-wide",
        aligned: false,
      },
    ],
    tier: "UNEXPLAINED",
    contributionTotal: 20,
    narratives: {
      "retail-ops":
        "Root isn't guessing on this one. AOV moved slightly but no candidate cause clears the evidence bar — top candidates are statistically indistinguishable from noise. Flagged for analyst review, no action recommended.",
      "retail-vp":
        "This AOV movement stays inside normal variance and no driver clears the confidence bar network-wide. Root is intentionally not attributing a cause here rather than offering a guess. Recommend routine monitoring only.",
    },
    action: {
      driver: "No candidate cause clears the evidence bar",
      lever: "—",
      action: "No action recommended — flagged for analyst review only",
      impact: "N/A",
      owner: "Data/Analytics team",
      confidence: "UNEXPLAINED · 20%",
      monitor: "Re-evaluate if AOV residual crosses 2.0σ",
    },
    checkBackDate: "2026-08-29",
  },
  "sc-stockout": {
    id: "case-sc-stockout-01",
    kpiId: "sc-stockout",
    domain: "supply-chain",
    title: "Stockout rate drifting up in DC-West",
    detect: {
      headline: "Stockout rate is 0.4pp above baseline for DC-West",
      statSignificance: "Residual exceeds 2.2σ control limit (bar: 2.0σ)",
      businessImpact: "~₹1.1L in expedited replenishment cost (bar: ₹1L)",
    },
    decompose: [
      { dimension: "Region", narrowedTo: "West", note: "Other regions flat" },
      { dimension: "SKU category", narrowedTo: "Fast-moving perishables", note: "62% of the drift isolates here" },
    ],
    evidence: [
      {
        kind: "structured",
        label: "WMS inbound events",
        detail: "Inbound receiving volume down slightly, within normal range",
        contribution: 30,
        citation: "wms_inbound_events · DC-West, wk 2026-08-17",
        aligned: true,
      },
      {
        kind: "unstructured",
        label: "Supplier notices",
        detail: "One supplier notice flags a short-term capacity constraint, timing partially overlaps",
        contribution: 25,
        citation: "supplier_notice #SN-1187",
        aligned: true,
      },
      {
        kind: "exogenous",
        label: "Weather / road closures",
        detail: "No coinciding event in the window",
        contribution: 0,
        citation: "regional_calendar · West, wk 2026-08-17",
        aligned: false,
      },
    ],
    tier: "SUSPECTED",
    contributionTotal: 55,
    narratives: {
      "sc-ops":
        "A supplier capacity constraint plausibly explains part of this, but the overlap with the timing isn't clean enough to call it confirmed. Keep an eye on fast-moving perishables in DC-West before pulling a backup supplier.",
      "sc-vp":
        "DC-West's stockout drift has a plausible but not yet confirmed cause (a supplier capacity notice). Not systemic — contained to one DC and one category. Recommend monitoring before any network-level supplier change.",
    },
    action: {
      driver: "Candidate: supplier capacity constraint, DC-West perishables — 55% combined contribution",
      lever: "Backup supplier activation",
      action: "Do not activate backup supplier yet — monitor inbound volume for 7 more days",
      impact: "Avoids an unnecessary supplier switch if the constraint resolves on its own",
      owner: "DC-West Ops Manager",
      confidence: "SUSPECTED · 55%",
      monitor: "Inbound receiving volume, DC-West perishables — check back in 7 days",
    },
    checkBackDate: "2026-08-29",
  },
  "sc-leadtime": {
    id: "case-sc-leadtime-01",
    kpiId: "sc-leadtime",
    domain: "supply-chain",
    title: "Lead-time variance drift, network-wide — no clear driver",
    detect: {
      headline: "Lead-time variance is trending up slightly but stays within normal envelope",
      statSignificance: "Residual at 1.2σ — below the 2.0σ materiality bar",
      businessImpact: "Below the ₹1L business-impact floor",
    },
    decompose: [
      { dimension: "Region", narrowedTo: "No single region isolates the movement", note: "Distributed evenly" },
      { dimension: "Supplier", narrowedTo: "No single supplier isolates the movement", note: "Distributed evenly" },
    ],
    evidence: [
      {
        kind: "structured",
        label: "ERP lead-time ledger",
        detail: "Minor variance increase across most suppliers, no outlier",
        contribution: 15,
        citation: "erp_po_ledger · network-wide, wk 2026-08-17",
        aligned: false,
      },
      {
        kind: "unstructured",
        label: "Carrier / DC incident tickets",
        detail: "No thematic signal above noise floor",
        contribution: 5,
        citation: "carrier_incident_tickets · low relevance",
        aligned: false,
      },
      {
        kind: "exogenous",
        label: "Weather / road closures",
        detail: "No coinciding signal",
        contribution: 0,
        citation: "regional_calendar · network-wide",
        aligned: false,
      },
    ],
    tier: "UNEXPLAINED",
    contributionTotal: 20,
    narratives: {
      "sc-ops":
        "No candidate cause clears the evidence bar for this drift — it's distributed evenly across suppliers and regions. Root is flagging it for analyst review rather than guessing.",
      "sc-vp":
        "This lead-time variance stays inside normal envelope and no driver clears the confidence bar network-wide. Recommend routine monitoring only, no supplier-level action.",
    },
    action: {
      driver: "No candidate cause clears the evidence bar",
      lever: "—",
      action: "No action recommended — flagged for analyst review only",
      impact: "N/A",
      owner: "Data/Analytics team",
      confidence: "UNEXPLAINED · 20%",
      monitor: "Re-evaluate if variance residual crosses 2.0σ",
    },
    checkBackDate: "2026-08-29",
  },
  "sc-cost": {
    id: "case-sc-cost-01",
    kpiId: "sc-cost",
    domain: "supply-chain",
    title: "Cost-per-order improves 1.1% network-wide",
    detect: {
      headline: "Cost-per-order is 1.1% below its STL-expected baseline, network-wide",
      statSignificance: "Residual exceeds 2.1σ control limit (bar: 2.0σ)",
      businessImpact: "~₹0.9L in weekly savings realized",
    },
    decompose: [
      { dimension: "Region", narrowedTo: "All regions", note: "Gain is broad-based, not isolated" },
      { dimension: "Lane", narrowedTo: "Consolidated long-haul lanes", note: "68% of the gain isolates here" },
    ],
    evidence: [
      {
        kind: "structured",
        label: "TMS carrier feed",
        detail: "Load consolidation on long-haul lanes increased, fewer partial-truck shipments",
        contribution: 68,
        citation: "tms_carrier_feed · network-wide, wk 2026-08-17",
        aligned: true,
      },
      {
        kind: "unstructured",
        label: "Carrier notices",
        detail: "No adverse notices; one carrier confirms a new consolidation program rollout",
        contribution: 12,
        citation: "supplier_notice #SN-1203",
        aligned: true,
      },
      {
        kind: "exogenous",
        label: "Weather / road closures",
        detail: "No coinciding signal",
        contribution: 0,
        citation: "regional_calendar · network-wide",
        aligned: false,
      },
    ],
    tier: "EXPLAINED",
    contributionTotal: 80,
    narratives: {
      "sc-ops":
        "The new load-consolidation program is working — fewer partial-truck shipments on long-haul lanes is driving the cost gain directly. No action needed; keep the program running as-is.",
      "sc-vp":
        "Network-wide cost-per-order improvement is explained by the load-consolidation program on long-haul lanes, not a one-off. Recommend expanding the program to more lanes given the confirmed gain.",
    },
    action: {
      driver: "Load consolidation, long-haul lanes — 80% combined contribution",
      lever: "Consolidation program expansion",
      action: "Expand load-consolidation program to additional long-haul lanes",
      impact: "~₹0.9L/week savings, scaling with expansion",
      owner: "VP Supply Chain",
      confidence: "EXPLAINED · 80%",
      monitor: "Cost-per-order, expanded lane set — check back in 2 weeks",
    },
    checkBackDate: "2026-09-05",
  },
};

export const domainLabels: Record<Domain, string> = {
  retail: "Retail / E-commerce",
  "supply-chain": "Supply Chain / Distribution",
};
